name: Build and Publish Python Package

# Trigger on push or pull request to main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - uses: actions/checkout@v4

      # 2️⃣ Setup Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # 3️⃣ Build the Python package
      - name: Build package
        run: |
          python -m pip install --upgrade pip build
          cd Assignment-2a           # <-- path to your package folder in repo
          python -m build            # creates dist/

      # 4️⃣ Publish to PyPI
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__                        # fixed username for API token
          password: ${{ secrets.PYPI_API_TOKEN }} # your PyPI API token stored in GitHub secrets
          packages-dir: Assignment-2a/dist/      # folder with .whl and .tar.gz files
